name: Docker CI/CD - Fullstack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials (from GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3️⃣ Fetch SSH secrets from AWS Secrets Manager
      - name: Fetch SSH secrets
        run: |
          aws secretsmanager get-secret-value \
            --secret-id fullstack/ssh \
            --query SecretString \
            --output text > ssh.json

          echo "SERVER_HOST=$(jq -r .SERVER_HOST ssh.json)" >> $GITHUB_ENV
          echo "SERVER_USER=$(jq -r .SERVER_USER ssh.json)" >> $GITHUB_ENV

          echo "$(jq -r .SERVER_SSH_KEY ssh.json)" > ssh_key
          chmod 600 ssh_key

      # 4️⃣ Copy docker-compose file to server
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key_path: ssh_key
          source: "docker-compose.yml"
          target: "/home/ubuntu/fullstack"

      # 5️⃣ Deploy on Ubuntu server
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key_path: ssh_key
          script: |
            cd /home/ubuntu/fullstack
            docker compose down
            docker compose up -d --build

