version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "🧩 Installing dependencies for frontend and backend..."
      - cd frontend
      - npm ci
      - npm run build
      - cd ../backend
      - npm ci
  build:
    commands:
      - echo "✅ Build completed successfully."
  post_build:
    commands:
      - echo "📦 Packaging build artifacts..."
artifacts:
  files:
    - '**/*'
