name: Fullstack CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend & Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # FRONTEND BUILD
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # BACKEND INSTALL
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            frontend/build
            backend

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: |
          npm ci
          npm test --if-present

      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          npm ci
          npm test --if-present

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/app"

      - name: Restart services on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/backend
            npm install --production
            pm2 restart backend || pm2 start server.js --name backend
            cd ../frontend
            npm install
            npm run build
            sudo systemctl restart nginx
